poll_app/poll_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

poll_app/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('<int:pk>/', views.DetailsView.as_view(), name = 'detail'),
    path('<int:pk>/result', views.ResultView.as_view(), name = 'result'),
    path('<int:q_id>/vote', views.vote, name = 'vote'),
]

poll_app/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class question(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('publication_date')

    def __str__(self):
        return "question text : " + self.question_text + "\npublication date : " + str(self.pub_date)

    def published_recent(self):
        return (timezone.now() - datetime.timedelta(days = 1)) <= self.pub_date <= timezone.now()

class choice(models.Model):
    question = models.ForeignKey(question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length = 200)
    votes = models.IntegerField(default = 0)

    def __str__(self):
        return "choice text : " + self.choice_text + "\nvotes : " + str(self.votes)

poll_app/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.template import loader

from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from .models import question, choice
from django.views import generic
from django.utils import timezone

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_questions'

    def get_queryset(self):
        return question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')

class ResultView(generic.DetailView):
    template_name = 'polls/results.html'
    model = question

class DetailsView(generic.DetailView):
    template_name = 'polls/details.html'
    model = question

def vote(request, q_id):
    ques = get_object_or_404(question, pk = q_id)

    try:
        selected = ques.choice_set.get(pk = request.POST['choice'])

    except (KeyError, choice.DoesNotExist):
        return render(request, 'polls/details.html', {'question' : ques, 'Error' : 'Invalid choice',})

    else:
        selected.votes += 1
        selected.save()
        return HttpResponseRedirect(reverse('polls:result', args=(q_id,)))

poll_app/polls/templates/polls/details.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<link type="text/css" rel="stylesheet" href="{% static 'polls/materialize.css' %}"  media="screen,projection"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

<body>
    <hr>
    <header class="blue-text text-darken-2"><marquee>This is a polling webapp made using Django</marquee></header>
    <hr>
    <br>
    <br>
<h5 class="z-depth-2"> Q. {{ question.id }}   {{ question.question_text }} </h5>

{% if error_message %} <p>{{ error_message }}</p> {% endif %}

<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %}

    {% for choice in question.choice_set.all %}
        <!-- <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label> <br> -->
        <p>
            <label>
              <input class="with-gap" name="choice" value="{{ choice.id }}" type="radio"/>
              <span>{{ choice.choice_text }}</span>
            </label>
          </p>
    {% endfor %}
    <br>
    <input class="btn-floating pulse" type="submit" value="Vote">
</form>
<br>
<a href="{% url 'polls:index' %}"> Back </a>
</body>

poll_app/polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<link type="text/css" rel="stylesheet" href="{% static 'polls/materialize.css' %}"  media="screen,projection"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

<body>
    <hr>
    <header class="blue-text text-darken-2"><marquee>This is a polling webapp made using Django</marquee></header>
    <hr>
    <br>
    <br>
    <h5 class="z-depth-2">Recent questions are : </h5>

    {% if latest_questions %}
    <ul>
        {% for question in latest_questions %}
            <li>Q.{{ forloop.counter }}   <a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
        {% endfor %}
    </ul>

    {% else %}
        <h1> No polls are available </h1>
    {% endif %}
    
    <hr>
    <footer id="footer">Made by: Mustafa Sadriwala &copy; Copyright 2020</footer>
    <hr>
</body>

poll_app/polls/templates/polls/results.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<link type="text/css" rel="stylesheet" href="{% static 'polls/materialize.css' %}"  media="screen,projection"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

<body>
    <hr>
    <header class="blue-text text-darken-2"><marquee>This is a polling webapp made using Django</marquee></header>
    <hr>
    <br>
    <br>
<h5> {{question.question_text}} </h5>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}   :   {{ choice.votes }}  vote{{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote Again</a>

<a href="{% url 'polls:index' %}"> Back to Homepage</a>

</body>